### ISSUE TITLE
InstagramAPI\Response\LoginResponse: Challenge required.

### ISSUE THREAD

**Issue by zProAle** [adrifkat/instagram-api#4]
how can I make the challenge request?

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/naer2/instagramStoryDownloader/blob/master/index.php#L82

**Comment by zProAle** [comment]
> https://github.com/naer2/instagramStoryDownloader/blob/master/index.php#L82

Thanks you

**Comment by recoverjp** [comment]
> > https://github.com/naer2/instagramStoryDownloader/blob/master/index.php#L82
> 
> Thanks you

You did it? Even implementing this, here continues with the challenge required.

**Comment by zProAle** [comment]
> 
> 
> > > https://github.com/naer2/instagramStoryDownloader/blob/master/index.php#L82
> > 
> > 
> > Thanks you
> 
> You did it? Even implementing this, here continues with the challenge required.

this https://github.com/zProAle/InstaLive-PHP/blob/master/live.php
