### ISSUE TITLE
Can´t loggin to instagram from instagram live php

### ISSUE THREAD

**Issue by joseemanuel0660** [adrifkat/instagram-api#5]
![image](https://user-images.githubusercontent.com/62640016/78079893-0fb65280-737b-11ea-9360-fc91c1451204.png)
Someone who can help me with this?

**Comment by mav123-dir** [comment]
same problem

**Comment by mav123-dir** [comment]
same problem

**Comment by zProAle** [comment]
Use my script on my profile

**Comment by joseemanuel0660** [comment]
thanks bro
